#! /bin/bash
#-------------------------------------------------------------------------------
#
# Script to simplfy ssh access to the simulation environment.  The spirit of this
# script can be used to create an entry in an ssh config file as well.
#
#-------------------------------------------------------------------------------

usage()
{
    [ "$*" == "" ] || {
	echo
	echo -e "ERROR: $*"
	echo
    }
    echo "sshelp - a utility simplifying ssh access to simulations"
    echo 
    echo "Usage"
    echo "    sshelp ssh"
    echo "    sshelp ssh-copy-id"
    echo "    sshelp scp sourcefile test:destfile"
    echo "    sshelp scp test:sourcefile destfile "
    echo
    echo "    Note that the scp variants are recursive"
    echo
    echo "The options specified are listed below; adding this to \$USER/.ssh/config"
    echo "will provide a more flexible solution; however, you\'ll have to manage "
    echo "the setup/cleanup manually."
    echo
    echo "    ForwardAgent yes"
    echo "    ForwardX11 yes"
    echo "    StrictHostKeyChecking no"
    echo "    UserKnownHostsFile /dev/null"
    echo "    User cumulus"
    echo "    LogLevel FATAL"
    echo 
    exit 1
}

# get the IP address of the oob-mgmt-server

IP_ADDR=$(vagrant ssh-config oob-mgmt-server |& sed -n -e "s/^ *HostName *//p")
[ "$IP_ADDR" != "" ] || {
    usage "Did not find the oob-mgmt-server info with \"vagrant ssh-config\""
}

# vet the command
case $1 in
    ssh)
	CMD=${1} && shift
	TARGET="test"
	;;
    ssh-copy-id)
	CMD=${1} && shift
	TARGET="test"
	;;
    scp)
	CMD=${1} && shift
	CMD+=" -r"
	SRC=${1} && shift
	DST=${1} && shift
	echo "${SRC} ${DST}"
	if [ "${SRC::5}" == "test:" ] && $(echo ${DST} | grep -v -q ":")
	then
	    :
	elif $(echo ${SRC} | grep -v -q ":") && [ "${DST::5}" == "test:" ]
	then
	    :
	else
	    usage "scp expects one of source or dest in the form \"test:file-dir\""
	fi
	TARGET="${SRC} ${DST}"
	;;
    *)
	usage "Do not understand command \"$1\""
esac

#enact the command

${CMD} \
    -o HostName=${IP_ADDR} \
    -o ForwardAgent=yes \
    -o ForwardX11=yes \
    -o StrictHostKeyChecking=no \
    -o UserKnownHostsFile=/dev/null \
    -o User=cumulus \
    -o LogLevel=FATAL \
    ${TARGET}

