#! /bin/bash

usage() {
    [ "$*" == "" ] || echo -e "\nERROR: $*\n"
    echo "usage: ${0}"
    echo "        where a Vagrant simulation is running in current working directory"
    exit 1
}

[ -e Vagrantfile ] || {
    usage "Vagrantfile does not exist"
}
ADDR=$(vagrant ssh-config oob-mgmt-server | sed -n -e "/HostName/s/^.* //p")
[ "$ADDR" != "" ] || {
    usage "Could not get IP address of oob-mgmt-server (is a simulation running?)"
}
NAME=$(basename $(realpath $PWD))
ssh-keygen -R $NAME
ssh-keygen -R $ADDR
sed -ie "/Host $NAME/,/^ *$/D" ~/.ssh/config
cat << EOF >> ~/.ssh/config
Host $NAME
    HostName $ADDR
    User cumulus
    ForwardAgent yes
    ForwardX11 yes
    UserKnownHostsFile /dev/null
    StrictHostKeyChecking no
    
EOF
ssh-copy-id ${NAME}


